spring:
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  jpa:
    open-in-view: false

qr-postcard:
  base-url: https://speaker.nantipov.org/postcard
  ipinfo-url: https://ipinfo.io/{ip}/json

logging:
  level:
    root: WARN
    org.nantipov: DEBUG
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%X){faint} %clr(%5p) %clr(${PID: }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
