spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    password: ${DB_USERNAME}
    username: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 30MB


qr-postcard:
  assets-dir: ${POSTCARD_ASSETS_DIR}

server:
  port: ${APP_PORT}
